const fs = require('fs');
const path = require('path');
const root = path.resolve(__dirname);
const write = (relativePath, lines) => {
  const filePath = path.join(root, relativePath);
  fs.writeFileSync(filePath, lines.join('\n'), 'utf8');
  console.log('Wrote', relativePath);
};

write('server.js', [
  "const express = require('express');",
  "const cors = require('cors');",
  "const helmet = require('helmet');",
  "const bcrypt = require('bcryptjs');",
  "const jwt = require('jsonwebtoken');",
  "const path = require('path');",
  "require('dotenv').config();",
  "",
  "const db = require('./database/db');",
  "const { authenticate, requireAdmin, JWT_SECRET } = require('./middleware/auth');",
  "",
  "const app = express();",
  "const PORT = process.env.PORT || 3000;",
  "",
  "app.disable('x-powered-by');",
  "app.set('trust proxy', 1);",
  "const allowedOrigin = process.env.ALLOWED_ORIGIN || (process.env.VERCEL_URL ? `https://${process.env.VERCEL_URL}` : 'http://localhost:3000');",
  "app.use(cors({ origin: allowedOrigin === '*' ? true : allowedOrigin, methods: ['GET','POST','PUT','DELETE','OPTIONS'], allowedHeaders: ['Content-Type','Authorization'], optionsSuccessStatus: 200 }));",
  "app.use(helmet({ contentSecurityPolicy: false }));",
  "app.use(express.json());",
  "app.use(express.static(path.join(__dirname, 'public')));",
  "",
  "const asyncHandler = (fn) => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);",
  "",
  "function normalizeParams(params) {",
  "  if (params === undefined || params === null) return [];",
  "  return Array.isArray(params) ? params : [params];",
  "}",
  "",
  "app.post('/api/auth/login', asyncHandler(async (req, res) => {",
  "  const { username, password } = req.body;",
  "  if (!username || !password) return res.status(400).json({ error: 'Username and password required' });",
  "  const user = await db.prepare('SELECT * FROM users WHERE username = ?').get([username]);",
  "  if (!user) return res.status(401).json({ error: 'Invalid credentials' });",
  "  const valid = bcrypt.compareSync(password, user.password);",
  "  if (!valid) return res.status(401).json({ error: 'Invalid credentials' });",
  "  if (user.status !== 'active') return res.status(403).json({ error: 'Account inactive' });",
  "",
  "  const token = jwt.sign({ id: user.id, username: user.username, role: user.role, full_name: user.full_name }, JWT_SECRET, { expiresIn: '7d' });",
  "",
  "  await db.prepare('INSERT INTO activities (user_id, action, description) VALUES (?, ?, ?)').run([user.id, 'login', `${user.full_name} logged in`]);",
  "",
  "  res.json({",
  "    token,",
  "    user: {",
  "      id: user.id,",
  "      username: user.username,",
  "      full_name: user.full_name,",
  "      email: user.email,",
  "      phone: user.phone,",
  "      role: user.role,",
  "      avatar_color: user.avatar_color",
  "    }",
  "  });",
  "}));",
  "",
  "app.get('/api/auth/me', authenticate, asyncHandler(async (req, res) => {",
  "  const user = await db.prepare('SELECT id, username, full_name, email, phone, role, avatar_color, created_at FROM users WHERE id = ?').get([req.user.id]);",
  "  res.json(user);",
  "}));",
  "",
  "app.get('/api/users', authenticate, requireAdmin, asyncHandler(async (req, res) => {",
  "  const users = await db.prepare(`",
  "    SELECT u.id, u.username, u.full_name, u.email, u.phone, u.role, u.avatar_color, u.status, u.created_at,",
  "           (SELECT COUNT(*) FROM clients WHERE assigned_to = u.id) as client_count,",
  "           (SELECT COUNT(*) FROM calls WHERE user_id = u.id) as call_count,",
  "           (SELECT COUNT(*) FROM meetings WHERE user_id = u.id) as meeting_count",
  "    FROM users u",
  "    ORDER BY u.role DESC, u.full_name",
  "  `).all();",
  "  res.json(users);",
  "}));",
  "",
  "app.post('/api/users', authenticate, requireAdmin, asyncHandler(async (req, res) => {",
  "  const { username, password, full_name, email, phone, role, avatar_color } = req.body;",
  "  if (!username || !password || !full_name) return res.status(400).json({ error: 'Username, password, and name required' });",
  "  const hashed = bcrypt.hashSync(password, 10);",
  "  const result = await db.prepare('INSERT INTO users (username, password, full_name, email, phone, role, avatar_color) VALUES (?, ?, ?, ?, ?, ?, ?)').run([username, hashed, full_name, email, phone, role || 'sales', avatar_color || '#6366f1']);",
  "  res.json({ id: result.lastInsertRowid });",
  "}));",
  "",
  "app.put('/api/users/:id', authenticate, requireAdmin, asyncHandler(async (req, res) => {",
  "  const { full_name, email, phone, role, avatar_color, status, password } = req.body;",
  "  if (password) {",
  "    const hashed = bcrypt.hashSync(password, 10);",
  "    await db.prepare('UPDATE users SET full_name = ?, email = ?, phone = ?, role = ?, avatar_color = ?, status = ?, password = ? WHERE id = ?').run([full_name, email, phone, role, avatar_color, status, hashed, req.params.id]);",
  "  } else {",
  "    await db.prepare('UPDATE users SET full_name = ?, email = ?, phone = ?, role = ?, avatar_color = ?, status = ? WHERE id = ?').run([full_name, email, phone, role, avatar_color, status, req.params.id]);",
  "  }",
  "  res.json({ success: true });",
  "}));",
  "",
  "app.get('/api/clients', authenticate, asyncHandler(async (req, res) => {",
  "  const { status, search } = req.query;",
  "  let query = 'SELECT c.*, u.full_name as assigned_to_name FROM clients c LEFT JOIN users u ON c.assigned_to = u.id WHERE 1=1';",
  "  const params = [];",
  "  if (req.user.role !== 'admin') { query += ' AND c.assigned_to = ?'; params.push(req.user.id); }",
  "  if (status) { query += ' AND c.status = ?'; params.push(status); }",
  "  if (search) { query += ' AND (c.name LIKE ? OR c.company LIKE ? OR c.email LIKE ?)'; const s = `%${search}%`; params.push(s, s, s); }",
  "  query += ' ORDER BY c.created_at DESC';",
  "  const clients = await db.prepare(query).all(params);",
  "  res.json(clients);",
  "}));",
  "",
  "app.get('/api/clients/:id', authenticate, asyncHandler(async (req, res) => {",
  "  const client = await db.prepare('SELECT c.*, u.full_name as assigned_to_name, u.email as assigned_to_email FROM clients c LEFT JOIN users u ON c.assigned_to = u.id WHERE c.id = ?').get([req.params.id]);",
  "  if (!client) return res.status(404).json({ error: 'Client not found' });",
  "  if (req.user.role !== 'admin' && client.assigned_to !== req.user.id) return res.status(403).json({ error: 'Access denied' });",
  "  const brief = await db.prepare('SELECT * FROM client_briefs WHERE client_id = ?').get([req.params.id]);",
  "  const calls = await db.prepare('SELECT calls.*, u.full_name as user_name FROM calls LEFT JOIN users u ON calls.user_id = u.id WHERE client_id = ? ORDER BY call_date DESC').all([req.params.id]);",
  "  const meetings = await db.prepare('SELECT meetings.*, u.full_name as user_name FROM meetings LEFT JOIN users u ON meetings.user_id = u.id WHERE client_id = ? ORDER BY meeting_date DESC').all([req.params.id]);",
  "  const todos = await db.prepare('SELECT * FROM todos WHERE client_id = ? ORDER BY due_date ASC').all([req.params.id]);",
  "  res.json({ ...client, brief, calls, meetings, todos });",
  "}));",
  "",
  "app.post('/api/clients', authenticate, asyncHandler(async (req, res) => {",
  "  const { name, company, email, phone, industry, status, source, estimated_value, notes, assigned_to } = req.body;",
  "  if (!name) return res.status(400).json({ error: 'Client name required' });",
  "  const assignedTo = req.user.role === 'admin' && assigned_to ? assigned_to : req.user.id;",
  "  const result = await db.prepare('INSERT INTO clients (name, company, email, phone, industry, status, source, assigned_to, estimated_value, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run([name, company, email, phone, industry, status || 'lead', source, assignedTo, estimated_value || 0, notes]);",
  "  res.json({ id: result.lastInsertRowid });",
  "}));",
  "",
  "app.put('/api/clients/:id', authenticate, asyncHandler(async (req, res) => {",
  "  const client = await db.prepare('SELECT * FROM clients WHERE id = ?').get([req.params.id]);",
  "  if (!client) return res.status(404).json({ error: 'Client not found' });",
  "  if (req.user.role !== 'admin' && client.assigned_to !== req.user.id) return res.status(403).json({ error: 'Access denied' });",
  "  const { name, company, email, phone, industry, status, source, estimated_value, notes, assigned_to } = req.body;",
  "  await db.prepare('UPDATE clients SET name = ?, company = ?, email = ?, phone = ?, industry = ?, status = ?, source = ?, estimated_value = ?, notes = ?, assigned_to = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?').run([name, company, email, phone, industry, status, source, estimated_value, notes, assigned_to || client.assigned_to, req.params.id]);",
  "  res.json({ success: true });",
  "}));",
  "",
  "app.get('/api/clients/:id/brief', authenticate, asyncHandler(async (req, res) => {",
  "  const client = await db.prepare('SELECT * FROM clients WHERE id = ?').get([req.params.id]);",
  "  if (!client) return res.status(404).json({ error: 'Client not found' });",
  "  if (req.user.role !== 'admin' && client.assigned_to !== req.user.id) return res.status(403).json({ error: 'Access denied' });",
  "  const brief = await db.prepare('SELECT * FROM client_briefs WHERE client_id = ?').get([req.params.id]);",
  "  res.json(brief || {});",
  "}));",
  "",
  "app.put('/api/clients/:id/brief', authenticate, asyncHandler(async (req, res) => {",
  "  const client = await db.prepare('SELECT * FROM clients WHERE id = ?').get([req.params.id]);",
  "  if (!client) return res.status(404).json({ error: 'Client not found' });",
  "  if (req.user.role !== 'admin' && client.assigned_to !== req.user.id) return res.status(403).json({ error: 'Access denied' });",
  "  const { budget, goals, target_audience, services_interested, current_challenges, competitors, preferences, internal_notes } = req.body;",
  "  const existing = await db.prepare('SELECT id FROM client_briefs WHERE client_id = ?').get([req.params.id]);",
  "  if (existing) {",
  "    await db.prepare('UPDATE client_briefs SET budget = ?, goals = ?, target_audience = ?, services_interested = ?, current_challenges = ?, competitors = ?, preferences = ?, internal_notes = ?, updated_at = CURRENT_TIMESTAMP WHERE client_id = ?').run([budget, goals, target_audience, services_interested, current_challenges, competitors, preferences, internal_notes, req.params.id]);",
  "  } else {",
  "    await db.prepare('INSERT INTO client_briefs (client_id, budget, goals, target_audience, services_interested, current_challenges, competitors, preferences, internal_notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)').run([req.params.id, budget, goals, target_audience, services_interested, current_challenges, competitors, preferences, internal_notes]);",
  "  }",
  "  res.json({ success: true });",
  "}));",
  "",
  "app.get('/api/calls', authenticate, asyncHandler(async (req, res) => {",
  "  const { client_id, user_id, from_date, to_date } = req.query;",
  "  let query = 'SELECT calls.*, c.name as client_name, c.company as client_company, u.full_name as user_name FROM calls LEFT JOIN clients c ON calls.client_id = c.id LEFT JOIN users u ON calls.user_id = u.id WHERE 1=1';",
  "  const params = [];",
  "  if (req.user.role !== 'admin') { query += ' AND calls.user_id = ?'; params.push(req.user.id); }",
  "  if (client_id) { query += ' AND calls.client_id = ?'; params.push(client_id); }",
  "  if (user_id) { query += ' AND calls.user_id = ?'; params.push(user_id); }",
  "  if (from_date) { query += ' AND call_date >= ?'; params.push(from_date); }",
  "  if (to_date) { query += ' AND call_date <= ?'; params.push(to_date); }",
  "  query += ' ORDER BY calls.call_date DESC LIMIT 200';",
  "  const rows = await db.prepare(query).all(params);",
  "  res.json(rows);",
  "}));",
  "",
  "app.post('/api/calls', authenticate, asyncHandler(async (req, res) => {",
  "  const { client_id, call_date, duration, call_type, outcome, subject, notes, next_follow_up } = req.body;",
  "  if (!client_id || !call_date) return res.status(400).json({ error: 'Client and date required' });",
  "  const result = await db.prepare('INSERT INTO calls (user_id, client_id, call_date, duration, call_type, outcome, subject, notes, next_follow_up) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)').run([req.user.id, client_id, call_date, duration || 0, call_type || 'outbound', outcome || 'connected', subject, notes, next_follow_up]);",
  "  res.json({ id: result.lastInsertRowid });",
  "}));",
  "",
  "app.put('/api/calls/:id', authenticate, asyncHandler(async (req, res) => {",
  "  const call = await db.prepare('SELECT * FROM calls WHERE id = ?').get([req.params.id]);",
  "  if (!call) return res.status(404).json({ error: 'Call not found' });",
  "  if (req.user.role !== 'admin' && call.user_id !== req.user.id) return res.status(403).json({ error: 'Access denied' });",
  "  const { call_date, duration, call_type, outcome, subject, notes, next_follow_up } = req.body;",
  "  await db.prepare('UPDATE calls SET call_date = ?, duration = ?, call_type = ?, outcome = ?, subject = ?, notes = ?, next_follow_up = ? WHERE id = ?').run([call_date, duration, call_type, outcome, subject, notes, next_follow_up, req.params.id]);",
  "  res.json({ success: true });",
  "}));",
  "",
  "app.delete('/api/calls/:id', authenticate, asyncHandler(async (req, res) => {",
  "  const call = await db.prepare('SELECT * FROM calls WHERE id = ?').get([req.params.id]);",
  "  if (!call) return res.status(404).json({ error: 'Call not found' });",
  "  if (req.user.role !== 'admin' && call.user_id !== req.user.id) return res.status(403).json({ error: 'Access denied' });",
  "  await db.prepare('DELETE FROM calls WHERE id = ?').run([req.params.id]);",
  "  res.json({ success: true });",
  "}));",
  "",
  "app.get('/api/meetings', authenticate, asyncHandler(async (req, res) => {",
  "  const { status, client_id, user_id, from_date, to_date } = req.query;",
  "  let query = 'SELECT meetings.*, c.name as client_name, c.company as client_company, u.full_name as user_name FROM meetings LEFT JOIN clients c ON meetings.client_id = c.id LEFT JOIN users u ON meetings.user_id = u.id WHERE 1=1';",
  "  const params = [];",
  "  if (req.user.role !== 'admin') { query += ' AND meetings.user_id = ?'; params.push(req.user.id); }",
  "  if (status) { query += ' AND meetings.status = ?'; params.push(status); }",
  "  if (client_id) { query += ' AND meetings.client_id = ?'; params.push(client_id); }",
  "  if (user_id) { query += ' AND meetings.user_id = ?'; params.push(user_id); }",
  "  if (from_date) { query += ' AND meeting_date >= ?'; params.push(from_date); }",
  "  if (to_date) { query += ' AND meeting_date <= ?'; params.push(to_date); }",
  "  query += ' ORDER BY meetings.meeting_date DESC LIMIT 200';",
  "  const rows = await db.prepare(query).all(params);",
  "  res.json(rows);",
  "}));",
  "",
  "app.post('/api/meetings', authenticate, asyncHandler(async (req, res) => {",
  "  const { client_id, title, meeting_date, duration, location, meeting_type, status, attendees, agenda, mom, decisions, action_items, next_meeting } = req.body;",
  "  if (!client_id || !title || !meeting_date) return res.status(400).json({ error: 'Required fields missing' });",
  "  const result = await db.prepare('INSERT INTO meetings (user_id, client_id, title, meeting_date, duration, location, meeting_type, status, attendees, agenda, mom, decisions, action_items, next_meeting) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run([req.user.id, client_id, title, meeting_date, duration || 60, location, meeting_type || 'in-person', status || 'scheduled', attendees, agenda, mom, decisions, action_items, next_meeting]);",
  "  res.json({ id: result.lastInsertRowid });",
  "}));",
  "",
  "app.put('/api/meetings/:id', authenticate, asyncHandler(async (req, res) => {",
  "  const meeting = await db.prepare('SELECT * FROM meetings WHERE id = ?').get([req.params.id]);",
  "  if (!meeting) return res.status(404).json({ error: 'Meeting not found' });",
  "  if (req.user.role !== 'admin' && meeting.user_id !== req.user.id) return res.status(403).json({ error: 'Access denied' });",
  "  const { title, meeting_date, duration, location, meeting_type, status, attendees, agenda, mom, decisions, action_items, next_meeting } = req.body;",
  "  await db.prepare('UPDATE meetings SET title = ?, meeting_date = ?, duration = ?, location = ?, meeting_type = ?, status = ?, attendees = ?, agenda = ?, mom = ?, decisions = ?, action_items = ?, next_meeting = ? WHERE id = ?').run([title, meeting_date, duration, location, meeting_type, status, attendees, agenda, mom, decisions, action_items, next_meeting, req.params.id]);",
  "  res.json({ success: true });",
  "}));",
  "",
  "app.delete('/api/meetings/:id', authenticate, asyncHandler(async (req, res) => {",
  "  const meeting = await db.prepare('SELECT * FROM meetings WHERE id = ?').get([req.params.id]);",
  "  if (!meeting) return res.status(404).json({ error: 'Meeting not found' });",
  "  if (req.user.role !== 'admin' && meeting.user_id !== req.user.id) return res.status(403).json({ error: 'Access denied' });",
  "  await db.prepare('DELETE FROM meetings WHERE id = ?').run([req.params.id]);",
  "  res.json({ success: true });",
  "}));",
  "",
  "app.get('/api/todos', authenticate, asyncHandler(async (req, res) => {",
  "  const { status, priority } = req.query;",
  "  let query = 'SELECT todos.*, c.name as client_name, u.full_name as user_name FROM todos LEFT JOIN clients c ON todos.client_id = c.id LEFT JOIN users u ON todos.user_id = u.id WHERE 1=1';",
  "  const params = [];",
  "  if (req.user.role !== 'admin') { query += ' AND todos.user_id = ?'; params.push(req.user.id); }",
  "  if (status) { query += ' AND todos.status = ?'; params.push(status); }",
  "  if (priority) { query += ' AND todos.priority = ?'; params.push(priority); }",
  "  query += ' ORDER BY todos.due_date ASC, todos.priority DESC';",
  "  const rows = await db.prepare(query).all(params);",
  "  res.json(rows);",
  "}));",
  "",
  "app.post('/api/todos', authenticate, asyncHandler(async (req, res) => {",
  "  const { title, description, due_date, priority, status, client_id, category } = req.body;",
  "  if (!title) return res.status(400).json({ error: 'Title required' });",
  "  const result = await db.prepare('INSERT INTO todos (user_id, title, description, due_date, priority, status, client_id, category) VALUES (?, ?, ?, ?, ?, ?, ?, ?)').run([req.user.id, title, description, due_date, priority || 'medium', status || 'pending', client_id, category]);",
  "  res.json({ id: result.lastInsertRowid });",
  "}));",
  "",
  "app.put('/api/todos/:id', authenticate, asyncHandler(async (req, res) => {",
  "  const todo = await db.prepare('SELECT * FROM todos WHERE id = ?').get([req.params.id]);",
  "  if (!todo) return res.status(404).json({ error: 'Todo not found' });",
  "  if (req.user.role !== 'admin' && todo.user_id !== req.user.id) return res.status(403).json({ error: 'Access denied' });",
  "  const { title, description, due_date, priority, status, client_id, category } = req.body;",
  "  const completed_at = status === 'completed' ? new Date().toISOString() : null;",
  "  await db.prepare('UPDATE todos SET title = ?, description = ?, due_date = ?, priority = ?, status = ?, client_id = ?, category = ?, completed_at = ? WHERE id = ?').run([title, description, due_date, priority, status, client_id, category, completed_at, req.params.id]);",
  "  res.json({ success: true });",
  "}));",
  "",
  "app.delete('/api/todos/:id', authenticate, asyncHandler(async (req, res) => {",
  "  const todo = await db.prepare('SELECT * FROM todos WHERE id = ?').get([req.params.id]);",
  "  if (!todo) return res.status(404).json({ error: 'Todo not found' });",
  "  if (req.user.role !== 'admin' && todo.user_id !== req.user.id) return res.status(403).json({ error: 'Access denied' });",
  "  await db.prepare('DELETE FROM todos WHERE id = ?').run([req.params.id]);",
  "  res.json({ success: true });",
  "}));",
  "",
  "app.get('/api/stats/dashboard', authenticate, asyncHandler(async (req, res) => {",
  "  const isAdmin = req.user.role === 'admin';",
  "  const today = new Date();",
  "  today.setHours(0, 0, 0, 0);",
  "  const tomorrow = new Date(today.getTime() + 86400000);",
  "  const weekAgo = new Date(today.getTime() - 6 * 86400000);",
  "  const monthAgo = new Date(today.getTime() - 29 * 86400000);",
  "",
  "  const userFilter = isAdmin ? '' : ' AND assigned_to = ?';",
  "  const userParams = isAdmin ? [] : [req.user.id];",
  "",
  "  const totalClients = await db.prepare(`SELECT COUNT(*) as c FROM clients WHERE 1=1${userFilter}`).get(userParams);",
  "  const activeClients = await db.prepare(`SELECT COUNT(*) as c FROM clients WHERE status IN ('active','prospect')${userFilter}`).get(userParams);",
  "  const totalCalls = await db.prepare(`SELECT COUNT(*) as c FROM calls WHERE 1=1${isAdmin ? '' : ' AND user_id = ?'}`).get(userParams);",
  "  const todayCalls = await db.prepare(`SELECT COUNT(*) as c FROM calls WHERE call_date >= ? AND call_date < ?${isAdmin ? '' : ' AND user_id = ?'}`).get([... (isAdmin ? [today.toISOString(), tomorrow.toISOString()] : [today.toISOString(), tomorrow.toISOString(), req.user.id])]);",
  "  const weekCalls = await db.prepare(`SELECT COUNT(*) as c FROM calls WHERE call_date >= ? AND call_date < ?${isAdmin ? '' : ' AND user_id = ?'}`).get([... (isAdmin ? [weekAgo.toISOString(), tomorrow.toISOString()] : [weekAgo.toISOString(), tomorrow.toISOString(), req.user.id])]);",
  "  const totalMeetings = await db.prepare(`SELECT COUNT(*) as c FROM meetings WHERE 1=1${isAdmin ? '' : ' AND user_id = ?'}`).get(userParams);",
  "  const upcomingMeetings = await db.prepare(`SELECT COUNT(*) as c FROM meetings WHERE meeting_date >= ? AND status = 'scheduled'${isAdmin ? '' : ' AND user_id = ?'}`).get([... (isAdmin ? [today.toISOString()] : [today.toISOString(), req.user.id])]);",
  "  const completedMeetings = await db.prepare(`SELECT COUNT(*) as c FROM meetings WHERE status = 'completed'${isAdmin ? '' : ' AND user_id = ?'}`).get(userParams);",
  "  const totalTodos = await db.prepare(`SELECT COUNT(*) as c FROM todos WHERE 1=1${isAdmin ? '' : ' AND user_id = ?'}`).get(userParams);",
  "  const pendingTodos = await db.prepare(`SELECT COUNT(*) as c FROM todos WHERE status = 'pending'${isAdmin ? '' : ' AND user_id = ?'}`).get(userParams);",
  "  const overdueTodos = await db.prepare(`SELECT COUNT(*) as c FROM todos WHERE status != 'completed' AND due_date < ?${isAdmin ? '' : ' AND user_id = ?'}`).get([... (isAdmin ? [today.toISOString().split('T')[0]] : [today.toISOString().split('T')[0], req.user.id])]);",
  "",
  "  const pipelineValue = await db.prepare(`SELECT COALESCE(SUM(estimated_value), 0) as v FROM clients WHERE status IN ('lead','prospect','active')${userFilter}`).get(userParams);",
  "",
  "  const callsByDay = await db.prepare(`SELECT date(call_date) as day, COUNT(*) as count FROM calls WHERE call_date >= ? AND call_date < ?${isAdmin ? '' : ' AND user_id = ?'} GROUP BY date(call_date) ORDER BY day ASC`).all([... (isAdmin ? [weekAgo.toISOString(), tomorrow.toISOString()] : [weekAgo.toISOString(), tomorrow.toISOString(), req.user.id])]);",
  "  const meetingsByStatus = await db.prepare(`SELECT status, COUNT(*) as count FROM meetings WHERE 1=1${isAdmin ? '' : ' AND user_id = ?'} GROUP BY status`).all(userParams);",
  "  const todosByPriority = await db.prepare(`SELECT priority, COUNT(*) as count FROM todos WHERE status != 'completed'${isAdmin ? '' : ' AND user_id = ?'} GROUP BY priority`).all(userParams);",
  "  const upcoming = await db.prepare(`SELECT meetings.*, c.name as client_name, c.company as client_company, u.full_name as user_name FROM meetings LEFT JOIN clients c ON meetings.client_id = c.id LEFT JOIN users u ON meetings.user_id = u.id WHERE meeting_date >= ? AND status = 'scheduled'${isAdmin ? '' : ' AND meetings.user_id = ?'} ORDER BY meetings.meeting_date ASC LIMIT 5`).all([... (isAdmin ? [today.toISOString()] : [today.toISOString(), req.user.id])]);",
  "  const recentCalls = await db.prepare(`SELECT calls.*, c.name as client_name, c.company as client_company, u.full_name as user_name FROM calls LEFT JOIN clients c ON calls.client_id = c.id LEFT JOIN users u ON calls.user_id = u.id WHERE 1=1${isAdmin ? '' : ' AND calls.user_id = ?'} ORDER BY calls.call_date DESC LIMIT 5`).all(userParams);",
  "  const pendingTodosList = await db.prepare(`SELECT todos.*, c.name as client_name, u.full_name as user_name FROM todos LEFT JOIN clients c ON todos.client_id = c.id LEFT JOIN users u ON todos.user_id = u.id WHERE todos.status != 'completed'${isAdmin ? '' : ' AND todos.user_id = ?'} ORDER BY todos.due_date ASC LIMIT 5`).all(userParams);",
  "",
  "  const result = {",
  "    totalClients: totalClients.c,",
  "    activeClients: activeClients.c,",
  "    totalCalls: totalCalls.c,",
  "    todayCalls: todayCalls.c,",
  "    weekCalls: weekCalls.c,",
  "    totalMeetings: totalMeetings.c,",
  "    upcomingMeetings: upcomingMeetings.c,",
  "    completedMeetings: completedMeetings.c,",
  "    totalTodos: totalTodos.c,",
  "    pendingTodos: pendingTodos.c,",
  "    overdueTodos: overdueTodos.c,",
  "    pipelineValue: pipelineValue.v || 0,",
  "    callsByDay,",
  "    meetingsByStatus,",
  "    todosByPriority,",
  "    upcomingMeetings: upcoming,",
  "    recentCalls,",
  "    pendingTodos: pendingTodosList",
  "  };",
  "",
  "  if (isAdmin) {",
  "    result.teamPerformance = await db.prepare(`",
  "      SELECT u.id, u.full_name, u.avatar_color,",
  "        (SELECT COUNT(*) FROM clients WHERE assigned_to = u.id) as clients,",
  "        (SELECT COUNT(*) FROM calls WHERE user_id = u.id) as calls,",
  "        (SELECT COUNT(*) FROM meetings WHERE user_id = u.id) as meetings,",
  "        (SELECT COUNT(*) FROM todos WHERE user_id = u.id AND status = 'completed') as todos_completed,",
  "        (SELECT COUNT(*) FROM todos WHERE user_id = u.id AND status != 'completed') as todos_pending,",
  "        (SELECT COALESCE(SUM(estimated_value), 0) FROM clients WHERE assigned_to = u.id) as pipeline",
  "      FROM users u",
  "      WHERE u.role = 'sales'",
  "      ORDER BY u.full_name",
  "    `).all();",
  "    result.recentActivities = await db.prepare(`",
  "      SELECT activities.*, u.full_name as user_name FROM activities LEFT JOIN users u ON activities.user_id = u.id ORDER BY activities.created_at DESC LIMIT 10",
  "    `).all();",
  "  }",
  "",
  "  res.json(result);",
  "}));",
  "",
  "app.get('/api/stats/team', authenticate, requireAdmin, asyncHandler(async (req, res) => {",
  "  const teamData = await db.prepare(`",
  "    SELECT u.id, u.full_name, u.avatar_color,",
  "      (SELECT COUNT(*) FROM clients WHERE assigned_to = u.id) as total_clients,",
  "      (SELECT COUNT(*) FROM clients WHERE assigned_to = u.id AND status = 'active') as active_clients,",
  "      (SELECT COUNT(*) FROM calls WHERE user_id = u.id AND call_date >= ?) as calls_30d,",
  "      (SELECT COUNT(*) FROM meetings WHERE user_id = u.id AND meeting_date >= ?) as meetings_30d,",
  "      (SELECT COUNT(*) FROM meetings WHERE user_id = u.id AND status = 'completed') as completed_meetings,",
  "      (SELECT COUNT(*) FROM todos WHERE user_id = u.id AND status = 'completed' AND completed_at >= ?) as todos_completed_30d,",
  "      (SELECT COALESCE(SUM(estimated_value), 0) FROM clients WHERE assigned_to = u.id AND status != 'inactive') as pipeline_value,",
  "      (SELECT COALESCE(SUM(duration), 0) FROM calls WHERE user_id = u.id AND call_date >= ?) as call_minutes_30d",
  "    FROM users u",
  "    WHERE u.role = 'sales'",
  "    ORDER BY pipeline_value DESC",
  "  `).all([new Date(Date.now() - 30 * 86400000).toISOString(), new Date(Date.now() - 30 * 86400000).toISOString(), new Date(Date.now() - 30 * 86400000).toISOString(), new Date(Date.now() - 30 * 86400000).toISOString()]);",
  "  res.json(teamData);",
  "}));",
  "",
  "app.get('/api/activities', authenticate, requireAdmin, asyncHandler(async (req, res) => {",
  "  const activities = await db.prepare('SELECT activities.*, u.full_name as user_name, u.avatar_color FROM activities LEFT JOIN users u ON activities.user_id = u.id ORDER BY activities.created_at DESC LIMIT 50').all();",
  "  res.json(activities);",
  "}));",
  "",
  "app.get('*', (req, res) => {",
  "  res.sendFile(path.join(__dirname, 'public', 'index.html'));",
  "});",
  "",
  "if (require.main === module) {",
  "  app.listen(PORT, () => {",
  "    console.log(`Limitless Sales System running on http://localhost:${PORT}`);",
  "  });",
  "}",
  "",
  "module.exports = app;"
]);

write(path.join('database', 'db.js'), [
  "const path = require('path');",
  "require('dotenv').config();",
  "",
  "const DATABASE_URL = process.env.DATABASE_URL;",
  "const isPostgres = Boolean(DATABASE_URL);",
  "",
  "let db = null;",
  "let ready = Promise.resolve();",
  "",
  "if (isPostgres) {",
  "  const { Pool } = require('pg');",
  "  const pool = new Pool({ connectionString: DATABASE_URL, ssl: { rejectUnauthorized: false } });",
  "",
  "  const schema = `",
  "CREATE TABLE IF NOT EXISTS users (",
  "  id SERIAL PRIMARY KEY,",
  "  username TEXT UNIQUE NOT NULL,",
  "  password TEXT NOT NULL,",
  "  full_name TEXT NOT NULL,",
  "  email TEXT UNIQUE,",
  "  phone TEXT,",
  "  role TEXT NOT NULL DEFAULT 'sales',",
  "  avatar_color TEXT DEFAULT '#6366f1',",
  "  status TEXT DEFAULT 'active',",
  "  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP",
  ");",
  "",
  "  const toPostgres = (sql) => {",
  "    let index = 0;",
  "    return sql.replace(/\?/g, () => '$' + ++index);",
  "  };",
  "",
  "  ready = pool.query(schema).catch((err) => { console.error('Postgres schema init failed:', err); throw err; });",
  "",
  "  db = {",
  "    isPostgres: true,",
  "    isSqlite: false,",
  "    ready,",
  "    prepare: (sql) => {",
  "      const pgSql = toPostgres(sql);",
  "      return {",
  "        all: async (params = []) => (await pool.query(pgSql, params)).rows,",
  "        get: async (params = []) => (await pool.query(pgSql, params)).rows[0] || null,",
  "        run: async (params = []) => {",
  "          let finalSql = pgSql;",
  "          if (/^\\s*INSERT\\s+/i.test(sql) && !/RETURNING\\s+/i.test(sql)) {",
  "            finalSql = finalSql.replace(/;?\\s*$/, ' RETURNING id');",
  "          }",
  "          const res = await pool.query(finalSql, params);",
  "          return { rowCount: res.rowCount, rows: res.rows, lastInsertRowid: res.rows[0]?.id };",
  "        }",
  "      };",
  "    },",
  "    all: async (sql, params = []) => (await pool.query(toPostgres(sql), params)).rows,",
  "    get: async (sql, params = []) => { const res = await pool.query(toPostgres(sql), params); return res.rows[0] || null; },",
  "    run: async (sql, params = []) => {",
  "      let finalSql = toPostgres(sql);",
  "      if (/^\\s*INSERT\\s+/i.test(sql) && !/RETURNING\\s+/i.test(sql)) {",
  "        finalSql = finalSql.replace(/;?\\s*$/, ' RETURNING id');",
  "      }",
  "      const res = await pool.query(finalSql, params);",
  "      return { rowCount: res.rowCount, rows: res.rows, lastInsertRowid: res.rows[0]?.id };",
  "    },",
  "    exec: async (sql) => { await pool.query(sql); },",
  "  };",
  "} else {",
  "  const Database = require('better-sqlite3');",
  "  const isVercel = process.env.VERCEL === '1' || Boolean(process.env.VERCEL_URL);",
  "  const dbPath = isVercel ? path.join('/tmp', 'limitless.db') : path.join(__dirname, 'limitless.db');",
  "  const sqlite = new Database(dbPath);",
  "  sqlite.pragma('foreign_keys = ON');",
  "",
  "  const schema = `",
  "CREATE TABLE IF NOT EXISTS users (",
  "  id INTEGER PRIMARY KEY AUTOINCREMENT,",
  "  username TEXT UNIQUE NOT NULL,",
  "  password TEXT NOT NULL,",
  "  full_name TEXT NOT NULL,",
  "  email TEXT UNIQUE,",
  "  phone TEXT,",
  "  role TEXT NOT NULL DEFAULT 'sales',",
  "  avatar_color TEXT DEFAULT '#6366f1',",
  "  status TEXT DEFAULT 'active',",
  "  created_at DATETIME DEFAULT CURRENT_TIMESTAMP",
  ");",
  "",
  "  sqlite.exec(schema);",
  "",
  "  db = {",
  "    isPostgres: false,",
  "    isSqlite: true,",
  "    ready,",
  "    prepare: (sql) => {",
  "      const stmt = sqlite.prepare(sql);",
  "      return {",
  "        all: async (params = []) => stmt.all(params),",
  "        get: async (params = []) => stmt.get(params),",
  "        run: async (params = []) => stmt.run(params),",
  "      };",
  "    },",
  "    all: async (sql, params = []) => sqlite.prepare(sql).all(params),",
  "    get: async (sql, params = []) => sqlite.prepare(sql).get(params),",
  "    run: async (sql, params = []) => sqlite.prepare(sql).run(params),",
  "    exec: async (sql) => sqlite.exec(sql),",
  "  };",
  "}",
  "",
  "module.exports = db;"
]);

write(path.join('database', 'seed.js'), [
  "const db = require('./db');",
  "const bcrypt = require('bcryptjs');",
  "",
  "async function runSeed() {",
  "  console.log('🌱 Seeding database...');",
  "",
  "  if (db.isPostgres) {",
  "    await db.exec('TRUNCATE TABLE activities, todos, meetings, calls, client_briefs, clients, users RESTART IDENTITY CASCADE;');",
  "  } else {",
  "    await db.exec(`",
  "      DELETE FROM activities;",
  "      DELETE FROM todos;",
  "      DELETE FROM meetings;",
  "      DELETE FROM calls;",
  "      DELETE FROM client_briefs;",
  "      DELETE FROM clients;",
  "      DELETE FROM users;",
  "    `);",
  "    await db.exec(`DELETE FROM sqlite_sequence WHERE name IN ('users','clients','client_briefs','calls','meetings','todos','activities');`);",
  "  }",
  "",
  "  const adminPlain = process.env.ADMIN_PASSWORD || 'Limitless@Admin2026!';",
  "  const salesPlain = process.env.SALES_PASSWORD || 'Sales@2026$';",
  "  const adminPass = bcrypt.hashSync(adminPlain, 10);",
  "  const salesPass = bcrypt.hashSync(salesPlain, 10);",
  "",
  "  const users = [",
  "    { username: 'admin', password: adminPass, full_name: 'Ahmed Hassan', email: 'ahmed@limitless.com', phone: '+201234567890', role: 'admin', avatar_color: '#ef4444' },",
  "    { username: 'sara', password: salesPass, full_name: 'Sara Mohamed', email: 'sara@limitless.com', phone: '+201111222333', role: 'sales', avatar_color: '#10b981' },",
  "    { username: 'omar', password: salesPass, full_name: 'Omar Ali', email: 'omar@limitless.com', phone: '+201222333444', role: 'sales', avatar_color: '#3b82f6' },",
  "    { username: 'lina', password: salesPass, full_name: 'Lina Khaled', email: 'lina@limitless.com', phone: '+201333444555', role: 'sales', avatar_color: '#8b5cf6' },",
  "    { username: 'mahmoud', password: salesPass, full_name: 'Mahmoud Said', email: 'mahmoud@limitless.com', phone: '+201444555666', role: 'sales', avatar_color: '#f59e0b' },",
  "  ];",
  "",
  "  const insertUser = db.prepare('INSERT INTO users (username, password, full_name, email, phone, role, avatar_color) VALUES (?, ?, ?, ?, ?, ?, ?)');",
  "  for (const u of users) { await insertUser.run([u.username, u.password, u.full_name, u.email, u.phone, u.role, u.avatar_color]); }",
  "  console.log('✅ Users created');",
  "",
  "  const clients = [",
  "    { name: 'Mohamed El-Sayed', company: 'TechVenture Egypt', email: 'mohamed@techventure.eg', phone: '+201090001001', industry: 'Technology', status: 'active', source: 'LinkedIn', assigned_to: 2, estimated_value: 150000, notes: 'Long-term contract potential' },",
  "    { name: 'Fatma Adel', company: 'Nile Fashion', email: 'fatma@nilefashion.com', phone: '+201090002002', industry: 'Fashion', status: 'prospect', source: 'Referral', assigned_to: 2, estimated_value: 85000, notes: 'Interested in social media campaign' },",
  "    { name: 'Karim Nabil', company: 'Cairo Bites', email: 'karim@cairobites.com', phone: '+201090003003', industry: 'Food & Beverage', status: 'lead', source: 'Website', assigned_to: 3, estimated_value: 45000, notes: 'New lead from contact form' },",
  "    { name: 'Nour Hassan', company: 'GreenLife Organic', email: 'nour@greenlife.eg', phone: '+201090004004', industry: 'Health', status: 'active', source: 'Cold Call', assigned_to: 3, estimated_value: 120000, notes: 'Premium client, monthly retainer' },",
  "    { name: 'Hany Mostafa', company: 'AutoDrive Motors', email: 'hany@autodrive.com', phone: '+201090005005', industry: 'Automotive', status: 'prospect', source: 'Event', assigned_to: 4, estimated_value: 200000, notes: 'Big budget, decision pending' },",
  "    { name: 'Yara Ibrahim', company: 'EduTech Plus', email: 'yara@edutechplus.com', phone: '+201090006006', industry: 'Education', status: 'lead', source: 'Facebook Ads', assigned_to: 4, estimated_value: 60000, notes: 'Looking for video production' },",
  "    { name: 'Tamer Farouk', company: 'Sunrise Hotels', email: 'tamer@sunrisehotels.com', phone: '+201090007007', industry: 'Hospitality', status: 'active', source: 'Referral', assigned_to: 5, estimated_value: 250000, notes: 'Multi-branch campaign' },",
  "    { name: 'Salma Galal', company: 'BeautyBox', email: 'salma@beautybox.com', phone: '+201090008008', industry: 'Beauty', status: 'prospect', source: 'Instagram', assigned_to: 5, estimated_value: 75000, notes: 'Influencer marketing interest' },",
  "  ];",
  "",
  "  const insertClient = db.prepare('INSERT INTO clients (name, company, email, phone, industry, status, source, assigned_to, estimated_value, notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');",
  "  for (const c of clients) { await insertClient.run([c.name, c.company, c.email, c.phone, c.industry, c.status, c.source, c.assigned_to, c.estimated_value, c.notes]); }",
  "  console.log('✅ Clients created');",
  "",
  "  const briefs = [",
  "    { client_id: 1, budget: '150,000 - 200,000 EGP/quarter', goals: 'Increase brand awareness by 40%, generate 500+ leads', target_audience: 'Tech-savvy millennials, Cairo & Alexandria', services_interested: 'Digital Marketing, SEO, Content Creation', current_challenges: 'Low brand recognition, competitors gaining market share', competitors: 'Vezeeta, Fareed, Uber Egypt', preferences: 'Data-driven approach, monthly reports', internal_notes: 'CEO is decision maker. Loves detailed analytics.' },",
  "    { client_id: 2, budget: '80,000 - 100,000 EGP', goals: 'Build Instagram presence, reach 100K followers', target_audience: 'Women 18-35, urban areas', services_interested: 'Social Media Management, Influencer Marketing', current_challenges: 'New brand, no online presence', competitors: 'Local fashion brands', preferences: 'Creative visuals, trendy content', internal_notes: 'Owner is very active on social media herself' },",
  "    { client_id: 3, budget: '40,000 - 50,000 EGP', goals: 'Launch new restaurant brand online', target_audience: 'Food lovers, Cairo residents', services_interested: 'Branding, Social Media Setup', current_challenges: 'Brand new business', competitors: 'Local restaurants with strong online presence', preferences: 'Affordable packages, quick turnaround', internal_notes: 'Startup, price-sensitive' },",
  "    { client_id: 4, budget: '120,000 - 150,000 EGP/month', goals: 'Maintain market leadership, expand to new cities', target_audience: 'Health-conscious families', services_interested: 'Full Digital Marketing, PR', current_challenges: 'Scaling operations', competitors: 'Major organic brands', preferences: 'Premium service quality', internal_notes: 'High-value client, weekly check-ins' },",
  "    { client_id: 5, budget: '200,000+ EGP', goals: 'Launch new SUV model campaign', target_audience: 'Upper-middle class car buyers', services_interested: 'Video Production, Event Marketing, Digital Ads', current_challenges: 'Entering competitive segment', competitors: 'Toyota, Hyundai, Kia', preferences: 'High production value', internal_notes: 'Auto industry experience required' },",
  "  ];",
  "",
  "  const insertBrief = db.prepare('INSERT INTO client_briefs (client_id, budget, goals, target_audience, services_interested, current_challenges, competitors, preferences, internal_notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)');",
  "  for (const b of briefs) { await insertBrief.run([b.client_id, b.budget, b.goals, b.target_audience, b.services_interested, b.current_challenges, b.competitors, b.preferences, b.internal_notes]); }",
  "  console.log('✅ Client briefs created');",
  "",
  "  const today = new Date();",
  "  const calls = [",
  "    { user_id: 2, client_id: 1, call_date: new Date(today.getTime() - 86400000).toISOString(), duration: 25, call_type: 'outbound', outcome: 'connected', subject: 'Q3 Campaign Discussion', notes: 'Discussed Q3 strategy. They want to push SEO focus. Will send proposal by Friday.', next_follow_up: new Date(today.getTime() + 3 * 86400000).toISOString().split('T')[0] },",
  "    { user_id: 2, client_id: 2, call_date: new Date(today.getTime() - 2 * 86400000).toISOString(), duration: 15, call_type: 'follow-up', outcome: 'connected', subject: 'Social Media Proposal', notes: 'Positive response to proposal. Wants to see influencer portfolio.', next_follow_up: new Date(today.getTime() + 86400000).toISOString().split('T')[0] },",
  "    { user_id: 3, client_id: 3, call_date: new Date(today.getTime() - 4 * 86400000).toISOString(), duration: 20, call_type: 'outbound', outcome: 'connected', subject: 'Initial Discussion', notes: 'Very interested. Asked for pricing details.', next_follow_up: new Date(today.getTime() + 2 * 86400000).toISOString().split('T')[0] },",
  "    { user_id: 3, client_id: 4, call_date: new Date(today.getTime() - 86400000).toISOString(), duration: 35, call_type: 'follow-up', outcome: 'connected', subject: 'Monthly Review', notes: 'Excellent results this month. Discussing expansion to Alexandria.', next_follow_up: new Date(today.getTime() + 7 * 86400000).toISOString().split('T')[0] },",
  "    { user_id: 4, client_id: 5, call_date: new Date(today.getTime() - 3 * 86400000).toISOString(), duration: 40, call_type: 'outbound', outcome: 'connected', subject: 'SUV Campaign Brief', notes: 'Need detailed campaign plan with video concepts. Big budget client.', next_follow_up: new Date(today.getTime() + 86400000).toISOString().split('T')[0] },",
  "    { user_id: 4, client_id: 6, call_date: new Date(today.getTime() - 5 * 86400000).toISOString(), duration: 12, call_type: 'outbound', outcome: 'voicemail', subject: 'Video Production Inquiry', notes: 'Left voicemail. Will retry tomorrow.', next_follow_up: new Date(today.getTime() + 86400000).toISOString().split('T')[0] },",
  "    { user_id: 5, client_id: 7, call_date: new Date(today.getTime() - 86400000).toISOString(), duration: 30, call_type: 'follow-up', outcome: 'connected', subject: 'Multi-branch Coordination', notes: 'Discussing rollout for 3 new branches. Need to schedule meeting.', next_follow_up: new Date(today.getTime() + 2 * 86400000).toISOString().split('T')[0] },",
  "    { user_id: 5, client_id: 8, call_date: new Date(today.getTime() - 2 * 86400000).toISOString(), duration: 18, call_type: 'outbound', outcome: 'callback', subject: 'Influencer Marketing', notes: 'Asked to call back after 3 PM. Will retry.', next_follow_up: null },",
  "    { user_id: 2, client_id: 1, call_date: new Date(today.getTime() - 7 * 86400000).toISOString(), duration: 22, call_type: 'follow-up', outcome: 'connected', subject: 'Contract Renewal', notes: 'Renewed contract for another 6 months. Great win!', next_follow_up: null },",
  "    { user_id: 3, client_id: 4, call_date: new Date(today.getTime() - 14 * 86400000).toISOString(), duration: 28, call_type: 'outbound', outcome: 'connected', subject: 'Strategy Sync', notes: 'Aligned on new content direction. Approved budget increase.', next_follow_up: null },",
  "  ];",
  "",
  "  const insertCall = db.prepare('INSERT INTO calls (user_id, client_id, call_date, duration, call_type, outcome, subject, notes, next_follow_up) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)');",
  "  for (const c of calls) { await insertCall.run([c.user_id, c.client_id, c.call_date, c.duration, c.call_type, c.outcome, c.subject, c.notes, c.next_follow_up]); }",
  "  console.log('✅ Calls created');",
  "",
  "  const meetings = [",
  "    { user_id: 2, client_id: 1, title: 'TechVenture - Q3 Strategy Meeting', meeting_date: new Date(today.getTime() + 2 * 86400000).toISOString(), duration: 90, location: 'Limitless Office - Meeting Room A', meeting_type: 'in-person', status: 'scheduled', attendees: 'Mohamed El-Sayed, Sara Mohamed, Strategy Team', agenda: '1. Q3 performance review\n2. Q4 strategy planning\n3. Budget allocation\n4. New campaign ideas', mom: null, decisions: null, action_items: null, next_meeting: new Date(today.getTime() + 30 * 86400000).toISOString().split('T')[0] },",
  "    { user_id: 2, client_id: 2, title: 'Nile Fashion - Influencer Strategy', meeting_date: new Date(today.getTime() - 3 * 86400000).toISOString(), duration: 60, location: 'Nile Fashion HQ', meeting_type: 'in-person', status: 'completed', attendees: 'Fatma Adel, Sara Mohamed', agenda: '1. Influencer shortlist review\n2. Content calendar\n3. Budget approval', mom: 'Meeting held at Nile Fashion HQ. Reviewed 15 potential influencers for Q4 campaign. Client approved top 5 selection. Discussed content calendar - 4 posts per week on Instagram, 2 reels weekly. Client excited about TikTok expansion.\n\nKey points:\n- Influencer budget: 40K EGP for 5 influencers\n- Content approval process: 24-hour turnaround\n- Launch date: October 15th', decisions: '1. Approved top 5 influencer selection\n2. Green-lit TikTok expansion with 50K budget\n3. Weekly content review calls starting next week', action_items: 'Sara: Send influencer contracts by Monday\nFatma: Provide brand guidelines document\nBoth: Schedule next review call for next Wednesday', next_meeting: new Date(today.getTime() + 7 * 86400000).toISOString().split('T')[0] },",
  "    { user_id: 3, client_id: 4, title: 'GreenLife - Monthly Performance Review', meeting_date: new Date(today.getTime() + 86400000).toISOString(), duration: 60, location: 'Zoom Meeting', meeting_type: 'video', status: 'scheduled', attendees: 'Nour Hassan, Omar Ali, Account Manager', agenda: '1. September performance metrics\n2. Alexandria expansion plan\n3. Budget review for Q4', mom: null, decisions: null, action_items: null, next_meeting: null },",
  "    { user_id: 4, client_id: 5, title: 'AutoDrive - SUV Campaign Kickoff', meeting_date: new Date(today.getTime() - 2 * 86400000).toISOString(), duration: 120, location: 'AutoDrive Showroom', meeting_type: 'in-person', status: 'completed', attendees: 'Hany Mostafa, Lina Khaled, Creative Director', agenda: '1. Campaign concept presentation\n2. Video production timeline\n3. Launch event planning', mom: 'Comprehensive kickoff meeting at AutoDrive showroom. Presented 3 campaign concepts - client selected Concept B (urban adventure theme). Discussed video production - 4 hero videos + 8 social cuts needed. Launch event planned for November 5th at City Stars.\n\nBudget breakdown:\n- Production: 80K EGP\n- Media buying: 100K EGP  \n- Event: 30K EGP', decisions: '1. Approved Concept B (urban adventure)\n2. Production timeline: Oct 1-25\n3. Launch event: Nov 5th at City Stars\n4. Hired external production house for hero videos', action_items: 'Lina: Finalize production crew by Sept 30\nHany: Provide product access for filming Oct 2\nCreative team: First cut by Oct 15', next_meeting: new Date(today.getTime() + 14 * 86400000).toISOString().split('T')[0] },",
  "    { user_id: 5, client_id: 7, title: 'Sunrise Hotels - Branch Expansion', meeting_date: new Date(today.getTime() + 4 * 86400000).toISOString(), duration: 90, location: 'Sunrise Hotels - Hurghada', meeting_type: 'in-person', status: 'scheduled', attendees: 'Tamer Farouk, Mahmoud Said, Regional Manager', agenda: '1. New branches opening strategy\n2. Unified branding approach\n3. Local vs national campaigns', mom: null, decisions: null, action_items: null, next_meeting: null },",
  "    { user_id: 3, client_id: 3, title: 'Cairo Bites - Brand Discovery', meeting_date: new Date(today.getTime() - 5 * 86400000).toISOString(), duration: 45, location: 'Cairo Bites Restaurant', meeting_type: 'in-person', status: 'completed', attendees: 'Karim Nabil, Omar Ali', agenda: '1. Brand vision discussion\n2. Target audience\n3. Initial budget planning', mom: 'Discovery session with Karim at the restaurant. Understood vision: authentic Egyptian street food experience elevated. Target: young professionals 25-35, food enthusiasts. Budget concerns but willing to start small.\n\nKey insights:\n- Strong personal brand potential for the owner\n- Unique recipes are differentiator\n- Limited initial budget but growth potential', decisions: '1. Start with 3-month pilot program\n2. Focus on Instagram first\n3. Create brand story content featuring Karim', action_items: 'Omar: Create 3-tier pricing options\nKarim: Provide high-quality food photos\nPilot launch: October 1st', next_meeting: new Date(today.getTime() + 7 * 86400000).toISOString().split('T')[0] },",
  "  ];",
  "",
  "  const insertMeeting = db.prepare('INSERT INTO meetings (user_id, client_id, title, meeting_date, duration, location, meeting_type, status, attendees, agenda, mom, decisions, action_items, next_meeting) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');",
  "  for (const m of meetings) { await insertMeeting.run([m.user_id, m.client_id, m.title, m.meeting_date, m.duration, m.location, m.meeting_type, m.status, m.attendees, m.agenda, m.mom, m.decisions, m.action_items, m.next_meeting]); }",
  "  console.log('✅ Meetings created');",
  "",
  "  const todos = [",
  "    { user_id: 2, title: 'Send TechVenture Q4 proposal', description: 'Include SEO package, content strategy, and budget breakdown', due_date: new Date(today.getTime() + 2 * 86400000).toISOString().split('T')[0], priority: 'high', status: 'pending', client_id: 1, category: 'Proposal' },",
  "    { user_id: 2, title: 'Follow up with Fatma on influencer contracts', description: 'Make sure contracts are signed before next week', due_date: new Date(today.getTime() + 86400000).toISOString().split('T')[0], priority: 'high', status: 'in-progress', client_id: 2, category: 'Follow-up' },",
  "    { user_id: 2, title: 'Prepare monthly report', description: 'Compile all client reports for September', due_date: new Date(today.getTime() + 5 * 86400000).toISOString().split('T')[0], priority: 'medium', status: 'pending', client_id: null, category: 'Admin' },",
  "    { user_id: 3, title: 'Send Cairo Bites pricing options', description: 'Create 3-tier pricing for their pilot program', due_date: new Date(today.getTime() + 3 * 86400000).toISOString().split('T')[0], priority: 'high', status: 'pending', client_id: 3, category: 'Proposal' },",
  "    { user_id: 3, title: 'Schedule GreenLife performance review', description: 'Send calendar invite for monthly meeting', due_date: new Date(today.getTime() + 86400000).toISOString().split('T')[0], priority: 'medium', status: 'completed', client_id: 4, category: 'Meeting' },",
  "    { user_id: 3, title: 'Research organic food industry trends', description: 'For GreenLife Q4 strategy', due_date: new Date(today.getTime() + 7 * 86400000).toISOString().split('T')[0], priority: 'low', status: 'pending', client_id: 4, category: 'Research' },",
  "    { user_id: 4, title: 'Finalize AutoDrive production crew', description: 'Confirm videographer, photographer, and drone operator', due_date: new Date(today.getTime() + 2 * 86400000).toISOString().split('T')[0], priority: 'high', status: 'pending', client_id: 5, category: 'Production' },",
  "    { user_id: 4, title: 'Call back Yara from EduTech', description: 'She requested a callback about video production', due_date: new Date(today.getTime() + 86400000).toISOString().split('T')[0], priority: 'medium', status: 'pending', client_id: 6, category: 'Follow-up' },",
  "    { user_id: 4, title: 'Create video concept deck', description: 'For EduTech Plus pitch', due_date: new Date(today.getTime() + 4 * 86400000).toISOString().split('T')[0], priority: 'medium', status: 'pending', client_id: 6, category: 'Creative' },",
  "    { user_id: 5, title: 'Prepare Hurghada trip presentation', description: 'Slides for Sunrise Hotels branch expansion meeting', due_date: new Date(today.getTime() + 3 * 86400000).toISOString().split('T')[0], priority: 'high', status: 'in-progress', client_id: 7, category: 'Presentation' },",
  "    { user_id: 5, title: 'Research hospitality marketing trends', description: 'Latest trends in hotel marketing for 2026', due_date: new Date(today.getTime() + 6 * 86400000).toISOString().split('T')[0], priority: 'low', status: 'pending', client_id: 7, category: 'Research' },",
  "    { user_id: 5, title: 'Send BeautyBox influencer proposal', description: 'Initial proposal after callback', due_date: new Date(today.getTime() + 4 * 86400000).toISOString().split('T')[0], priority: 'medium', status: 'pending', client_id: 8, category: 'Proposal' },",
  "    { user_id: 2, title: 'Update CRM with new leads', description: 'Add 5 leads from LinkedIn campaign', due_date: new Date(today.getTime() - 86400000).toISOString().split('T')[0], priority: 'low', status: 'completed', client_id: null, category: 'Admin' },",
  "    { user_id: 3, title: 'Send GreenLink content calendar', description: 'October content plan', due_date: new Date(today.getTime() + 5 * 86400000).toISOString().split('T')[0], priority: 'medium', status: 'pending', client_id: 4, category: 'Content' },",
  "  ];",
  "",
  "  const insertTodo = db.prepare('INSERT INTO todos (user_id, title, description, due_date, priority, status, client_id, category) VALUES (?, ?, ?, ?, ?, ?, ?, ?)');",
  "  for (const t of todos) { await insertTodo.run([t.user_id, t.title, t.description, t.due_date, t.priority, t.status, t.client_id, t.category]); }",
  "  console.log('✅ Todos created');",
  "",
  "  console.log('\\n🎉 Database seeded successfully!');",
  "  console.log('\\n📝 Login credentials:');",
  "  console.log(`   Admin:  username=admin,  password=${adminPlain}`);",
  "  console.log(`   Sales:  username=sara,   password=${salesPlain}`);",
  "  console.log(`   Sales:  username=omar,   password=${salesPlain}`);",
  "  console.log(`   Sales:  username=lina,   password=${salesPlain}`);",
  "  console.log(`   Sales:  username=mahmoud, password=${salesPlain}`);",
  "}",
  "",
  "runSeed().catch(err => { console.error(err); process.exit(1); });"
]);
